# Generated by Django 3.1.6 on 2021-02-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=20)),
                ('fone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controle_estagios.endereco')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.IntegerField(unique=True)),
                ('data_nascimento', models.DateField(default=True)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=13)),
            ],
            bases=('controle_estagios.endereco',),
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controle_estagios.endereco')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
            ],
            bases=('controle_estagios.endereco',),
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controle_estagios.endereco')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
            ],
            bases=('controle_estagios.endereco',),
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controle_estagios.endereco')),
                ('nome', models.CharField(max_length=50)),
                ('id_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estagios.instituicao')),
            ],
            bases=('controle_estagios.endereco',),
        ),
        migrations.CreateModel(
            name='Estagios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_prorrogacao', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estagios.alunos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estagios.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('unidades', models.ManyToManyField(to='controle_estagios.Unidades')),
            ],
        ),
        migrations.AddField(
            model_name='alunos',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estagios.cursos'),
        ),
    ]
