# Generated by Django 3.1.6 on 2021-02-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estagios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
