# Generated by Django 3.1.6 on 2021-02-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estagios', '0003_auto_20210211_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='fone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
