# Generated by Django 3.1.6 on 2021-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estagios', '0004_auto_20210223_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
