# Generated by Django 3.1.6 on 2021-03-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estagios', '0008_auto_20210310_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='instituicao',
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
